'use strict';

/**
 * HTTP Status Codes — Use these instead of magic numbers.
 */
const HttpStatus = Object.freeze({
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
});

/**
 * Internal Error Codes — Every error in the system has a unique code.
 * Format: DOMAIN_ACTION_ISSUE
 * These are used in API responses, logs, and monitoring.
 */
const ErrorCodes = Object.freeze({
  // --- Authentication ---
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  AUTH_REFRESH_EXPIRED: 'AUTH_REFRESH_EXPIRED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_2FA_REQUIRED: 'AUTH_2FA_REQUIRED',
  AUTH_2FA_INVALID: 'AUTH_2FA_INVALID',
  AUTH_2FA_ALREADY_ENABLED: 'AUTH_2FA_ALREADY_ENABLED',
  AUTH_IP_NOT_WHITELISTED: 'AUTH_IP_NOT_WHITELISTED',
  AUTH_SESSION_INVALID: 'AUTH_SESSION_INVALID',

  // --- Authorization (RBAC) ---
  RBAC_INSUFFICIENT_PERMISSIONS: 'RBAC_INSUFFICIENT_PERMISSIONS',
  RBAC_ROLE_NOT_FOUND: 'RBAC_ROLE_NOT_FOUND',
  RBAC_ACCESS_DENIED: 'RBAC_ACCESS_DENIED',

  // --- Validation ---
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_MISSING_FIELD: 'VALIDATION_MISSING_FIELD',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',

  // --- Merchant ---
  MERCHANT_NOT_FOUND: 'MERCHANT_NOT_FOUND',
  MERCHANT_DISABLED: 'MERCHANT_DISABLED',
  MERCHANT_INACTIVE: 'MERCHANT_INACTIVE',
  MERCHANT_SUSPENDED: 'MERCHANT_SUSPENDED',
  MERCHANT_PENDING_APPROVAL: 'MERCHANT_PENDING_APPROVAL',
  MERCHANT_API_KEY_INVALID: 'MERCHANT_API_KEY_INVALID',
  MERCHANT_API_KEY_NOT_FOUND: 'MERCHANT_API_KEY_NOT_FOUND',
  MERCHANT_API_KEY_LIMIT: 'MERCHANT_API_KEY_LIMIT',
  MERCHANT_HMAC_INVALID: 'MERCHANT_HMAC_INVALID',
  MERCHANT_NONCE_REUSED: 'MERCHANT_NONCE_REUSED',
  MERCHANT_TIMESTAMP_EXPIRED: 'MERCHANT_TIMESTAMP_EXPIRED',
  MERCHANT_KEY_EXPIRED: 'MERCHANT_KEY_EXPIRED',
  MERCHANT_IP_BLOCKED: 'MERCHANT_IP_BLOCKED',
  MERCHANT_WITHDRAWAL_ADDRESS_MISSING: 'MERCHANT_WITHDRAWAL_ADDRESS_MISSING',
  MERCHANT_WITHDRAWAL_ADDRESS_UNVERIFIED: 'MERCHANT_WITHDRAWAL_ADDRESS_UNVERIFIED',
  MERCHANT_WEBHOOK_URL_REQUIRED: 'MERCHANT_WEBHOOK_URL_REQUIRED',

  // --- Payment / Invoice ---
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  INVOICE_EXPIRED: 'INVOICE_EXPIRED',
  INVOICE_ALREADY_PAID: 'INVOICE_ALREADY_PAID',
  INVOICE_ALREADY_CANCELLED: 'INVOICE_ALREADY_CANCELLED',
  INVOICE_CANNOT_CANCEL: 'INVOICE_CANNOT_CANCEL',
  INVOICE_CANCELLED: 'INVOICE_CANCELLED',
  INVOICE_AMOUNT_POOL_EXHAUSTED: 'INVOICE_AMOUNT_POOL_EXHAUSTED',
  INVOICE_CREATION_FAILED: 'INVOICE_CREATION_FAILED',
  INVOICE_CREATION_PAUSED: 'INVOICE_CREATION_PAUSED',

  // --- Transaction ---
  TX_NOT_FOUND: 'TX_NOT_FOUND',
  TX_ALREADY_MATCHED: 'TX_ALREADY_MATCHED',
  TX_UNDERPAID: 'TX_UNDERPAID',
  TX_OVERPAID: 'TX_OVERPAID',
  TX_LATE_PAYMENT: 'TX_LATE_PAYMENT',
  TX_DUPLICATE: 'TX_DUPLICATE',
  TX_MATCHING_FAILED: 'TX_MATCHING_FAILED',

  // --- Wallet ---
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_DISABLED: 'WALLET_DISABLED',
  WALLET_BALANCE_EXCEEDED: 'WALLET_BALANCE_EXCEEDED',
  WALLET_DECRYPTION_FAILED: 'WALLET_DECRYPTION_FAILED',

  // --- Withdrawal ---
  WITHDRAWAL_INSUFFICIENT_BALANCE: 'WITHDRAWAL_INSUFFICIENT_BALANCE',
  WITHDRAWAL_RATE_LIMITED: 'WITHDRAWAL_RATE_LIMITED',
  WITHDRAWAL_COOLDOWN_ACTIVE: 'WITHDRAWAL_COOLDOWN_ACTIVE',
  WITHDRAWAL_APPROVAL_REQUIRED: 'WITHDRAWAL_APPROVAL_REQUIRED',
  WITHDRAWAL_ADDRESS_NOT_VERIFIED: 'WITHDRAWAL_ADDRESS_NOT_VERIFIED',
  WITHDRAWAL_SIGNING_FAILED: 'WITHDRAWAL_SIGNING_FAILED',
  WITHDRAWAL_BROADCAST_FAILED: 'WITHDRAWAL_BROADCAST_FAILED',
  WITHDRAWAL_DISPUTED_FUNDS: 'WITHDRAWAL_DISPUTED_FUNDS',

  // --- Signing ---
  SIGNING_REQUEST_INVALID: 'SIGNING_REQUEST_INVALID',
  SIGNING_KEY_DECRYPTION_FAILED: 'SIGNING_KEY_DECRYPTION_FAILED',
  SIGNING_RATE_LIMITED: 'SIGNING_RATE_LIMITED',

  // --- Blockchain ---
  BLOCKCHAIN_API_FAILED: 'BLOCKCHAIN_API_FAILED',
  BLOCKCHAIN_STALE_DATA: 'BLOCKCHAIN_STALE_DATA',
  BLOCKCHAIN_REORG_DETECTED: 'BLOCKCHAIN_REORG_DETECTED',
  BLOCKCHAIN_INSUFFICIENT_ENERGY: 'BLOCKCHAIN_INSUFFICIENT_ENERGY',

  // --- Reconciliation ---
  RECON_MISMATCH_DETECTED: 'RECON_MISMATCH_DETECTED',
  RECON_API_FAILURE: 'RECON_API_FAILURE',

  // --- Dispute ---
  DISPUTE_NOT_FOUND: 'DISPUTE_NOT_FOUND',
  DISPUTE_ALREADY_RESOLVED: 'DISPUTE_ALREADY_RESOLVED',
  DISPUTE_DEADLINE_PASSED: 'DISPUTE_DEADLINE_PASSED',

  // --- Webhook ---
  WEBHOOK_DELIVERY_FAILED: 'WEBHOOK_DELIVERY_FAILED',
  WEBHOOK_URL_INVALID: 'WEBHOOK_URL_INVALID',
  WEBHOOK_DELIVERY_NOT_FOUND: 'WEBHOOK_DELIVERY_NOT_FOUND',
  WEBHOOK_RETRY_NOT_ALLOWED: 'WEBHOOK_RETRY_NOT_ALLOWED',
  WEBHOOK_TEST_FAILED: 'WEBHOOK_TEST_FAILED',

  // --- User Management ---
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_CANNOT_DELETE_SELF: 'USER_CANNOT_DELETE_SELF',
  USER_CANNOT_MODIFY_SUPER_ADMIN: 'USER_CANNOT_MODIFY_SUPER_ADMIN',
  USER_SESSIONS_REVOKED: 'USER_SESSIONS_REVOKED',

  // --- System Config ---
  CONFIG_KEY_NOT_FOUND: 'CONFIG_KEY_NOT_FOUND',
  CONFIG_KEY_READONLY: 'CONFIG_KEY_READONLY',
  CONFIG_VALUE_INVALID: 'CONFIG_VALUE_INVALID',
  SYSTEM_INVOICES_PAUSED: 'SYSTEM_INVOICES_PAUSED',
  SYSTEM_WITHDRAWALS_PAUSED: 'SYSTEM_WITHDRAWALS_PAUSED',

  // --- Reconciliation ---
  RECON_MISMATCH_DETECTED: 'RECON_MISMATCH_DETECTED',
  RECON_API_FAILURE: 'RECON_API_FAILURE',
  RECON_ALREADY_RUNNING: 'RECON_ALREADY_RUNNING',
  RECON_REPORT_NOT_FOUND: 'RECON_REPORT_NOT_FOUND',

  // --- System ---
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  CONFIG_INVALID: 'CONFIG_INVALID',
  RATE_LIMITED: 'RATE_LIMITED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
});

module.exports = { HttpStatus, ErrorCodes };
